anchor_version = "0.24.2"
solana_version = "1.10.30"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cardinal_token_manager = "9KU8ogB4tKAgfxxz94dWq7V5UDB41kMyDeAtq3xMwnjh"
cardinal_paid_claim_approver = "ASARc3C85tapTVLHLfDMdzxiNCjJDM4C7ZmEZNJ5g9FV"
cardinal_time_invalidator = "5Jd9DPJ7Q99dNBRso8Xm1ZE215GRjbtkdPEz8U5QWZfU"
cardinal_use_invalidator = "7Qt3zVnqXuxqtzZy8iMyhnFfHdcv2UdqweoHvHKtiah1"
cardinal_payment_manager = 'tzVYw3v7AHVXWdVTEQS4uwM5woPK3NJwBELAE9Mv4tW'
cardinal_transfer_authority = '638EtvgGQTmc2jc9SdAPtLSCjSXRrkyBfSd54xP2pquZ'