anchor_version = "0.24.2"
solana_version = "1.10.30"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cardinal_token_manager = "9o2MLDQPyUDwuV81zcfn7dHx6ZS4mm2U9w3QoxUHB8U1"
cardinal_paid_claim_approver = "4ZtHLgmEHpsNejeduUJwEmpXLv1vZMcoFbJUEus9BGL8"
cardinal_time_invalidator = "GLm4LAnymyxCcwuu1uKtBf5dCRYbdNuXdamPbifwXdRv"
cardinal_use_invalidator = "B8gTHHQmz2UsvXxk4NqfuKgLLapKePt7c33zwW4NNU5M"
cardinal_payment_manager = 'DRxWY9ThgdfARwKVkUC7RYFVCxGrKdAUErHtkjDAaFAB'
cardinal_transfer_authority = 'A1eisbUwy27tgVzL8xH9YY92HWqUZZEarFgbL4WVoEQz'